databases:
  - name: emart
    databaseName: emart
    user: emart

services:
  - type: web
    name: emart
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rail s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emart
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction